FROM python:3.12-alpine

# hadolint ignore=DL3018
RUN apk add --no-cache \
    gcc \
    musl-dev \
    python3-dev \
    postgresql-dev \
    && rm -rf /var/cache/apk/*

RUN pip install --no-cache-dir psycopg2==2.9.9

CMD ["python"]
